// <auto-generated />
using System;
using MarmorariaProjeto.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarmorariaProjeto.Migrations
{
    [DbContext(typeof(MarmorariaDbContext))]
    partial class MarmorariaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarmorariaProjeto.Domain.Entities.HistoricoEntrada", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<long>("ItemEstoqueId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ItensEstoqueId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItensEstoqueId");

                    b.ToTable("HistoricosEntrada");
                });

            modelBuilder.Entity("MarmorariaProjeto.Domain.Entities.HistoricoSaida", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Funcionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ItemEstoqueId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ItensEstoqueId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItensEstoqueId");

                    b.ToTable("HistoricosSaida");
                });

            modelBuilder.Entity("MarmorariaProjeto.Domain.Entities.ItensEstoque", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeAtual")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ItensEstoque");
                });

            modelBuilder.Entity("MarmorariaProjeto.Domain.Entities.HistoricoEntrada", b =>
                {
                    b.HasOne("MarmorariaProjeto.Domain.Entities.ItensEstoque", "ItensEstoque")
                        .WithMany()
                        .HasForeignKey("ItensEstoqueId");

                    b.Navigation("ItensEstoque");
                });

            modelBuilder.Entity("MarmorariaProjeto.Domain.Entities.HistoricoSaida", b =>
                {
                    b.HasOne("MarmorariaProjeto.Domain.Entities.ItensEstoque", "ItensEstoque")
                        .WithMany()
                        .HasForeignKey("ItensEstoqueId");

                    b.Navigation("ItensEstoque");
                });
#pragma warning restore 612, 618
        }
    }
}
